# Generated by Django 3.0.7 on 2020-06-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='tittle',
            new_name='title',
        ),
    ]
